import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import glob from "fast-glob";
import chokidar from "chokidar";
import type { FSWatcher } from "chokidar";
import type { Plugin } from "vite";

export const PLUGIN_CONFIG = {
  name: "mockup-preview",
  mockupsDir: "src/components/mockups",
  generatedModule: "src/.generated/mockup-components.ts",
  localhostUrl: "http://127.0.0.1",
  watcher: {
    stabilityThreshold: 100,
    pollInterval: 50,
  },
} as const;

interface DiscoveredComponent {
  globKey: string;
  importPath: string;
}

function getMockupsAbsDir(root: string): string {
  return path.join(root, PLUGIN_CONFIG.mockupsDir);
}

function getGeneratedModuleAbsPath(root: string): string {
  return path.join(root, PLUGIN_CONFIG.generatedModule);
}

function isMockupFile(absolutePath: string, root: string): boolean {
  const rel = path.relative(getMockupsAbsDir(root), absolutePath);
  return !rel.startsWith("..") && !path.isAbsolute(rel) && rel.endsWith(".tsx");
}

function isPreviewTarget(relativeToMockups: string): boolean {
  return relativeToMockups.split(path.sep).every((segment) => !segment.startsWith("_"));
}

async function discoverComponents(root: string): Promise<Array<DiscoveredComponent>> {
  const files = await glob(`${PLUGIN_CONFIG.mockupsDir}/**/*.tsx`, {
    cwd: root,
    ignore: ["**/_*/**", "**/_*.tsx"],
  });

  return files.map((f) => ({
    globKey: "./" + f.slice("src/".length),
    importPath: path.posix.relative("src/.generated", f),
  }));
}

function generateSource(components: Array<DiscoveredComponent>): string {
  const entries = components
    .map((c) => `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`)
    .join(",\n");

  return [
    "// This file is auto-generated by mockup-preview-plugin.ts.",
    "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
    "export const modules: ModuleMap = {",
    entries,
    "};",
    "",
  ].join("\n");
}

function shouldAutoRescan(pathname: string): boolean {
  return (
    pathname.includes("/components/mockups/") || pathname.includes("/.generated/mockup-components")
  );
}

class MockupPreviewManager {
  private root = "";
  private currentSource = "";
  private watcher: FSWatcher | null = null;
  private refreshInFlight = false;
  private refreshQueued = false;

  setRoot(root: string): void {
    this.root = root;
  }

  async refresh(): Promise<boolean> {
    if (this.refreshInFlight) {
      this.refreshQueued = true;
      return false;
    }

    this.refreshInFlight = true;
    let changed = false;
    try {
      const components = await discoverComponents(this.root);
      const newSource = generateSource(components);
      if (newSource !== this.currentSource) {
        this.currentSource = newSource;
        const generatedModuleAbsPath = getGeneratedModuleAbsPath(this.root);
        mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
        writeFileSync(generatedModuleAbsPath, this.currentSource);
        changed = true;
      }
    } finally {
      this.refreshInFlight = false;
    }

    if (this.refreshQueued) {
      this.refreshQueued = false;
      const followUp = await this.refresh();
      return changed || followUp;
    }

    return changed;
  }

  async startWatcher(): Promise<void> {
    const mockupsAbsDir = getMockupsAbsDir(this.root);
    mkdirSync(mockupsAbsDir, { recursive: true });

    this.watcher = chokidar.watch(mockupsAbsDir, {
      ignoreInitial: true,
      awaitWriteFinish: {
        stabilityThreshold: PLUGIN_CONFIG.watcher.stabilityThreshold,
        pollInterval: PLUGIN_CONFIG.watcher.pollInterval,
      },
    });

    this.watcher.on("add", (file) => {
      if (isMockupFile(file, this.root) && isPreviewTarget(path.relative(mockupsAbsDir, file))) {
        void this.refresh();
      }
    });

    this.watcher.on("unlink", (file) => {
      if (isMockupFile(file, this.root)) {
        void this.refresh();
      }
    });
  }

  async closeWatcher(): Promise<void> {
    if (this.watcher) {
      await this.watcher.close();
      this.watcher = null;
    }
  }
}

export function mockupPreviewPlugin(): Plugin {
  const manager = new MockupPreviewManager();

  return {
    name: PLUGIN_CONFIG.name,
    enforce: "pre",

    configResolved(config) {
      manager.setRoot(config.root);
    },

    async buildStart() {
      await manager.refresh();
    },

    async configureServer(viteServer) {
      await manager.refresh();
      await manager.startWatcher();

      viteServer.middlewares.use((req, res, next) => {
        const requestUrl = new URL(req.url ?? "/", PLUGIN_CONFIG.localhostUrl);
        const pathname = requestUrl.pathname;
        const originalEnd = res.end.bind(res);

        res.end = ((...args: Parameters<typeof originalEnd>) => {
          if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
            void manager.refresh();
          }
          return originalEnd(...args);
        }) as typeof res.end;

        next();
      });
    },

    async closeWatcher() {
      await manager.closeWatcher();
    },
  };
}
