export const PLUGIN_NAME = "mockup-preview";
export const DEV_SERVER_LOCALHOST_URL = "http://127.0.0.1";

export const WATCHER_STABILITY_THRESHOLD_MS = 100;
export const WATCHER_POLL_INTERVAL_MS = 50;
export const WATCHER_ERROR_LOG_PREFIX = "[mockup-preview-plugin] watcher error:";

export const GENERATED_DIR_NAME = ".generated";
export const GENERATED_MODULE_BASENAME = "mockup-components";
export const GENERATED_FILE_EXTENSION = ".ts";

export const GENERATED_FILE_HEADER = "// This file is auto-generated by mockup-preview-plugin.ts.";
export const GENERATED_MODULE_MAP_TYPE =
  "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;";
export const GENERATED_MODULES_EXPORT_OPEN = "export const modules: ModuleMap = {";
export const GENERATED_MODULES_EXPORT_CLOSE = "};";
