/**
 * Skill file templates for `docuvia-*` skill set (issue #50, roadmap item 30).
 *
 * Each skill mirrors the shape of the existing `.claude/skills/no-magic-strings/` precedent:
 * a `SKILL.md` with YAML frontmatter (`name` + `description`) followed by structured guidance.
 * Skills are installed as project-local files under `.claude/skills/` via `docuvia init --skills`
 * and removed via `docuvia uninstall --skills`.
 *
 * Why these exist: task-routed skill files let an agent get guided on which command/format
 * fits a given task, instead of relying solely on the AGENTS.md/CLAUDE.md prose mandate
 * which can get dropped from a long conversation's live context.
 */

export const SKILLS_DIR_NAME = "docuvia";

export interface SkillTemplate {
  /** Directory name under `.claude/skills/` */
  dirName: string;
  /** Full SKILL.md content (frontmatter + body) */
  content: string;
}

const EXPLORING_CONTENT = [
  "---",
  "name: docuvia-exploring",
  "description: >",
  "  Use when exploring or navigating an unfamiliar codebase -- before reaching for",
  "  Grep, Glob, or Read. Queries the local Docuvia knowledge graph for concepts,",
  "  files, and symbols, and checks blast radius before editing. Falls back to raw",
  "  file tools only when the graph returns nothing or the target is flagged unprocessed.",
  "---",
  "",
  "# Explore the Codebase via Docuvia",
  "",
  "## When to use this skill",
  "",
  "You are exploring, navigating, or learning about a codebase. Before any Grep, Glob, or Read",
  "call, query the knowledge graph first -- it is structurally aware and orders of magnitude",
  "cheaper than raw file scanning.",
  "",
  "## Exploration workflow",
  "",
  "**Step 1 -- Query the graph for the concept.**",
  "",
  "Use the `docuvia_query` MCP tool (or CLI fallback):",
  "```",
  'npx --no-install docuvia query "<concept_or_file>" --format=prompt',
  "```",
  "",
  "The result includes `match_type` (exact/keyword/neighbor) -- treat a non-`exact` match on",
  "what should be a well-known symbol as a signal to cross-check with Grep/Glob.",
  "",
  "**Step 2 -- Check blast radius before editing.**",
  "",
  "Before modifying any file or symbol, run:",
  "```",
  "npx --no-install docuvia impact <symbolOrFile>",
  "```",
  "",
  "This returns which other parts of the codebase would be affected, with a risk level",
  "assessment. Stop and warn the user if it comes back HIGH or CRITICAL.",
  "",
  "**Step 3 -- Only fall back to raw file tools when:**",
  "",
  "- The graph returns empty results",
  '- The target is flagged `tier_b_status="unprocessed"` (unknown, not zero)',
  "- You need exact source text, formatting, or a diff",
  "- `query` returns a non-`exact` `match_type` for what should be a well-known symbol",
  "",
  "## After making code changes",
  "",
  "If your change reflects a real architectural decision, rule, or notable rationale, stage it:",
  "",
  "```",
  "npx --no-install docuvia analyze <file> --agent-authored --stage",
  "```",
  "",
  "Pipe a JSON payload on stdin or pass `--decisions-file=<path>`. Staged decisions flush",
  "into the knowledge graph automatically on the next commit touching that file.",
].join("\n");

const IMPACT_ANALYSIS_CONTENT = [
  "---",
  "name: docuvia-impact-analysis",
  "description: >",
  "  Use before making any code change to analyze blast radius -- which other parts of",
  "  the codebase would be affected, with a risk level assessment. Also use after",
  "  receiving a code review or diff to understand downstream impact.",
  "---",
  "",
  "# Impact Analysis with Docuvia",
  "",
  "## When to use this skill",
  "",
  "You are about to modify code, or you have received a review/diff and need to understand",
  "downstream impact. Always run impact analysis before touching shared interfaces, constants,",
  "or widely-imported modules.",
  "",
  "## Impact analysis workflow",
  "",
  "**Step 1 -- Run impact analysis on the target.**",
  "",
  "```",
  "npx --no-install docuvia impact <symbolOrFile>",
  "```",
  "",
  'Or via MCP: `docuvia_impact` with `{ "target": "<symbolOrFile>" }`',
  "",
  "The result includes:",
  "- `blastRadius`: array of affected nodes with filePath, edgeType, and depth",
  "- `riskLevel`: LOW / MEDIUM / HIGH / CRITICAL",
  "- L3 decision context explaining *why* each dependent matters",
  "",
  "**Step 2 -- Assess the risk level.**",
  "",
  "- **LOW**: Safe to proceed -- changes are localized",
  "- **MEDIUM**: Review the affected files -- some cross-cutting concern may exist",
  "- **HIGH**: Stop and warn the user -- significant downstream impact detected",
  "- **CRITICAL**: Do not proceed without explicit user confirmation",
  "",
  "**Step 3 -- Cross-reference with query if needed.**",
  "",
  "If impact returns unexpected results or you need more context on a specific dependent,",
  "query the graph:",
  "```",
  'npx --no-install docuvia query "<dependent_symbol>" --format=prompt',
  "```",
  "",
  "**Step 4 -- After changes, stage decisions.**",
  "",
  "If your change reflects architectural rationale, stage it for the knowledge graph:",
  "```",
  "npx --no-install docuvia analyze <file> --agent-authored --stage",
  "```",
].join("\n");

const KNOWLEDGE_GRAPH_CONTENT = [
  "---",
  "name: docuvia-knowledge-graph",
  "description: >",
  "  Use when querying the Docuvia knowledge graph -- guides effective query construction,",
  "  result interpretation (match types, L2/L3 data), and when to cross-check with raw",
  "  file tools.",
  "---",
  "",
  "# Querying the Knowledge Graph",
  "",
  "## When to use this skill",
  "",
  "You need to look up a concept, file, symbol, or architectural decision in the codebase.",
  "The knowledge graph provides structural awareness that Grep/Glob/Read cannot match.",
  "",
  "## Query workflow",
  "",
  "**Step 1 -- Construct a targeted query.**",
  "",
  "Use the `docuvia_query` MCP tool (or CLI fallback):",
  "```",
  'npx --no-install docuvia query "<target>" --format=prompt',
  "```",
  "",
  "Tips for effective queries:",
  '- Use exact symbol names for best results (`match_type: "exact"`)',
  "- Concept phrases work but may return `keyword` matches -- cross-check those",
  "- File paths resolve to their containing module's structural data",
  "- Use `--limit=N` to cap results when exploring broadly",
  "",
  "**Step 2 -- Interpret the result.**",
  "",
  "Each result includes:",
  "- `matchType`: `exact` (high confidence) / `keyword` (medium) / `neighbor` (low)",
  "- `node`: L2 structural data (type, filePath, key)",
  "- `l3Decisions`: L3 rationale if available (why this code exists)",
  "",
  "**Step 3 -- Decide trust level.**",
  "",
  '- `matchType: "exact"` on a well-known symbol -> trust it',
  '- `matchType: "keyword"` or `"neighbor"` -> cross-check with Grep/Glob',
  "- Empty result -> fall back to raw file tools",
  '- `tier_b_status: "unprocessed"` -> graph has not seen this file yet, treat as unknown',
  "",
  "**Step 4 -- Use impact for dependency analysis.**",
  "",
  "After finding a symbol, check who depends on it:",
  "```",
  "npx --no-install docuvia impact <symbolOrFile>",
  "```",
].join("\n");

const AGENT_AUTHORED_CONTENT = [
  "---",
  "name: docuvia-agent-authored",
  "description: >",
  "  Use after making code changes that reflect architectural decisions, rules, or",
  "  notable rationale -- stages L3 decisions into the knowledge graph for future",
  "  query/impact context. Supports both MCP tool and CLI fallback.",
  "---",
  "",
  "# Stage Agent-Authored L3 Decisions",
  "",
  "## When to use this skill",
  "",
  "You have just made (or are about to commit) a code change that reflects:",
  "- An architectural decision (why this approach was chosen)",
  "- A rule or constraint (what must not be changed)",
  "- Context that future agents need (why this code exists this way)",
  "",
  "## Staging decisions",
  "",
  "**Option A -- MCP tool (preferred, when available):**",
  "",
  "Use `docuvia_apply_decision` with:",
  "```json",
  "{",
  '  "targetPath": "src/path/to/file.ts",',
  '  "decisions": [',
  "    {",
  '      "title": "Decision title",',
  '      "content": "Detailed rationale",',
  '      "nodeType": "decision",',
  '      "confidence": 0.9',
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "**Option B -- CLI fallback:**",
  "",
  "```",
  "npx --no-install docuvia analyze <file> --agent-authored --stage",
  "```",
  "",
  "Pipe JSON on stdin or use `--decisions-file=<path>`.",
  "",
  "**Option C -- CLI (direct write, no staging):**",
  "",
  "```",
  "npx --no-install docuvia analyze <file> --agent-authored",
  "```",
  "",
  "## Decision fields",
  "",
  "- `title`: Short description of the decision",
  "- `content`: Detailed rationale -- why this approach was chosen",
  "- `nodeType`: One of `change`, `rule`, `decision`, `context`",
  "- `confidence`: 0.0 to 1.0 -- how certain you are about this rationale",
  "",
  "## How it works",
  "",
  "Staged decisions (Options A/B) are flushed into `l3_nodes` automatically on the next git",
  "commit that touches the target file -- via the post-commit hook's `--flush-staged-l3` step.",
  "No manual flush step needed.",
  "",
  "Direct writes (Option C) persist immediately to `l3_nodes` with `source='agent-authored'`.",
].join("\n");

export const DOCUVIA_SKILL_TEMPLATES: SkillTemplate[] = [
  {
    dirName: "docuvia-exploring",
    content: EXPLORING_CONTENT,
  },
  {
    dirName: "docuvia-impact-analysis",
    content: IMPACT_ANALYSIS_CONTENT,
  },
  {
    dirName: "docuvia-knowledge-graph",
    content: KNOWLEDGE_GRAPH_CONTENT,
  },
  {
    dirName: "docuvia-agent-authored",
    content: AGENT_AUTHORED_CONTENT,
  },
];
