/**
 * Tree-sitter node `.type` discriminants compared/dispatched on across ast-core's
 * cross-language parsing (edge-computer.ts, semantic-diff.ts) — grammar-level
 * values, not ours to rename. See `lib/core`'s `AstNodeTypes` (`ast-constants.ts`)
 * for the same convention.
 */
export const TreeSitterNodeTypes = {
  IDENTIFIER: "identifier",
  SCOPED_IDENTIFIER: "scoped_identifier",
  QUALIFIED_IDENTIFIER: "qualified_identifier",
  DOTTED_NAME: "dotted_name",
  ALIASED_IMPORT: "aliased_import",
  USE_AS_CLAUSE: "use_as_clause",
  USE_WILDCARD: "use_wildcard",
  SCOPED_USE_LIST: "scoped_use_list",
  USE_LIST: "use_list",
  DOT: "dot",
  BLANK_IDENTIFIER: "blank_identifier",
  NAMESPACE_USE_DECLARATION: "namespace_use_declaration",
  INCLUDE_EXPRESSION: "include_expression",
  INCLUDE_ONCE_EXPRESSION: "include_once_expression",
  REQUIRE_EXPRESSION: "require_expression",
  REQUIRE_ONCE_EXPRESSION: "require_once_expression",
  IMPORT_STATEMENT: "import_statement",
  IMPORT_FROM_STATEMENT: "import_from_statement",
  USE_DECLARATION: "use_declaration",
  IMPORT_DECLARATION: "import_declaration",
  PREPROC_INCLUDE: "preproc_include",
  USING_DECLARATION: "using_declaration",
  CALL: "call",
  USING_DIRECTIVE: "using_directive",
  CALL_EXPRESSION: "call_expression",
  METHOD_INVOCATION: "method_invocation",
  EXPLICIT_CONSTRUCTOR_INVOCATION: "explicit_constructor_invocation",
  COMMAND_CALL: "command_call",
  FUNCTION_CALL_EXPRESSION: "function_call_expression",
  MEMBER_CALL_EXPRESSION: "member_call_expression",
  SCOPED_CALL_EXPRESSION: "scoped_call_expression",
  INVOCATION_EXPRESSION: "invocation_expression",
  OBJECT_CREATION_EXPRESSION: "object_creation_expression",
  MEMBER_EXPRESSION: "member_expression",
  ATTRIBUTE: "attribute",
  MEMBER_ACCESS_EXPRESSION: "member_access_expression",
  VARIABLE_DECLARATION: "variable_declaration",
  LEXICAL_DECLARATION: "lexical_declaration",
  VARIABLE_DECLARATOR: "variable_declarator",
  ARROW_FUNCTION: "arrow_function",
  FUNCTION_DECLARATION: "function_declaration",
  METHOD_DEFINITION: "method_definition",
  CLASS_DECLARATION: "class_declaration",
  INTERFACE_DECLARATION: "interface_declaration",
  TYPE_ALIAS_DECLARATION: "type_alias_declaration",
  EXPORT_STATEMENT: "export_statement",
} as const;
