import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import l1TagsRouter from "./l1_tags";
import l2NodesRouter from "./l2_nodes";
import l3NodesRouter from "./l3_nodes";
import reviewTasksRouter from "./review_tasks";
import ingestRouter from "./ingest";
import generateRouter from "./generate";
import searchRouter from "./search";
import mcpRouter from "./mcp";
import llmConfigRouter from "./llm_config";
import exportRouter from "./export";
import templatesRouter from "./templates";
import subscriptionsRouter from "./subscriptions";
import notificationsRouter from "./notifications";
import pullRequestsRouter from "./pull_requests";
import extensionsVscodeRouter from "./extensions_vscode";
import integrationsRouter from "./integrations";
import syncRouter from "./sync";
import documentsRouter from "./documents";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(projectsRouter);
router.use(l1TagsRouter);
router.use(l2NodesRouter);
router.use(l3NodesRouter);
router.use(reviewTasksRouter);
router.use(ingestRouter);
router.use(generateRouter);
router.use(searchRouter);
router.use(mcpRouter);
router.use(llmConfigRouter);
router.use(exportRouter);
router.use(templatesRouter);
router.use(subscriptionsRouter);
router.use(notificationsRouter);
router.use(pullRequestsRouter);
router.use(extensionsVscodeRouter);
router.use(integrationsRouter);
router.use(syncRouter);
router.use(documentsRouter);

export default router;
