export const AST_NODE_TYPES = {
  ALIASED_IMPORT: "aliased_import",
  ASTERISK: "asterisk",
  ATTRIBUTE: "attribute",
  BLANK_IDENTIFIER: "blank_identifier",
  CALL: "call",
  CALL_EXPRESSION: "call_expression",
  COMMAND_CALL: "command_call",
  DOT: "dot",
  DOTTED_NAME: "dotted_name",
  FIELD_EXPRESSION: "field_expression",
  FUNCTION_CALL_EXPRESSION: "function_call_expression",
  IDENTIFIER: "identifier",
  IMPORT_DECLARATION: "import_declaration",
  IMPORT_FROM_STATEMENT: "import_from_statement",
  IMPORT_SPEC: "import_spec",
  IMPORT_SPEC_LIST: "import_spec_list",
  IMPORT_SPECIFIER: "import_specifier",
  IMPORT_STATEMENT: "import_statement",
  INCLUDE_EXPRESSION: "include_expression",
  INCLUDE_ONCE_EXPRESSION: "include_once_expression",
  INVOCATION_EXPRESSION: "invocation_expression",
  MEMBER_ACCESS_EXPRESSION: "member_access_expression",
  MEMBER_CALL_EXPRESSION: "member_call_expression",
  MEMBER_EXPRESSION: "member_expression",
  METHOD_INVOCATION: "method_invocation",
  NAME: "name",
  NAMED_IMPORTS: "named_imports",
  NAMESPACE_IMPORT: "namespace_import",
  NAMESPACE_USE_DECLARATION: "namespace_use_declaration",
  OBJECT_CREATION_EXPRESSION: "object_creation_expression",
  PREPROC_INCLUDE: "preproc_include",
  QUALIFIED_IDENTIFIER: "qualified_identifier",
  QUALIFIED_NAME: "qualified_name",
  REQUIRE_EXPRESSION: "require_expression",
  REQUIRE_ONCE_EXPRESSION: "require_once_expression",
  SCOPED_CALL_EXPRESSION: "scoped_call_expression",
  SCOPED_IDENTIFIER: "scoped_identifier",
  SCOPED_USE_LIST: "scoped_use_list",
  SELECTOR_EXPRESSION: "selector_expression",
  STRING: "string",
  STRING_CONTENT: "string_content",
  USE_AS_CLAUSE: "use_as_clause",
  USE_DECLARATION: "use_declaration",
  USE_WILDCARD: "use_wildcard",
  USING_DECLARATION: "using_declaration",
  USING_DIRECTIVE: "using_directive",
  WILDCARD_IMPORT: "wildcard_import",
} as const;

export const AST_FIELD_NAMES = {
  ALIAS: "alias",
  ARGUMENT: "argument",
  ARGUMENTS: "arguments",
  ATTRIBUTE: "attribute",
  EXPRESSION: "expression",
  FIELD: "field",
  FUNCTION: "function",
  LIST: "list",
  METHOD: "method",
  MODULE_NAME: "module_name",
  NAME: "name",
  OBJECT: "object",
  PATH: "path",
  PROPERTY: "property",
  RECEIVER: "receiver",
  SCOPE: "scope",
  TYPE: "type",
  VALUE: "value",
} as const;

export const AST_EVENTS = {
  FILE: "file",
  IMPORT: "import",
  CLASS: "class",
  FUNCTION: "function",
  METHOD_CALL: "method_call",
  CALL: "call",
  API_CONTRACT: "api_contract",
} as const;

export const AST_STATUS = {
  DONE: "done",
  ERROR: "error",
} as const;

export const AST_MESSAGES = {
  REGISTRY_UNINITIALIZED: "Language registry not initialized",
  GRAMMAR_LOAD_FAILED: "Failed to load grammar WASM",
  PARSE_FAILED: "Failed to parse file with tree-sitter",
  GRAMMAR_NOT_FOUND: "Language grammar not found for extension",
} as const;
