import { eq } from "drizzle-orm";
import { l1TagsTable, reviewTasksTable, activityLogTable } from "@workspace/db";
import {
  IL1ProcessingService,
  ILlmGenerationService,
} from "../../interfaces/knowledge-generation.interfaces.js";
import { getPromptTemplate } from "../prompt-service.js";
import { generateEmbedding, cosineSimilarity } from "../embedding.js";

export class L1ProcessingService implements IL1ProcessingService {
  constructor(private readonly llmGenerationService: ILlmGenerationService) {}

  async processL1Tagger(
    tx: any,
    projectId: number,
    projectName: string,
    commitData: any[],
    model: string,
    similarityThreshold: number
  ): Promise<{ l1TagsCreated: number; reviewTasksCreated: number; tagMap: Map<string, number> }> {
    let l1TagsCreated = 0;
    let reviewTasksCreated = 0;
    const tagMap = new Map<string, number>();

    const l1SystemPrompt = await getPromptTemplate(projectId, "l1_tagger");
    const existingL1 = await tx.select().from(l1TagsTable);
    const existingTagNames = existingL1.map((t: any) => t.name);

    const aiL1Tags = await this.llmGenerationService.generateL1Tags(
      projectId,
      commitData,
      existingTagNames,
      model,
      l1SystemPrompt
    );

    for (const existing of existingL1) {
      tagMap.set(existing.name.toLowerCase(), existing.id);
    }

    const existingL1Embeddings = await Promise.all(
      existingL1.map(async (tag: any) => ({
        id: tag.id,
        embedding: await generateEmbedding(
          projectId,
          `${tag.name} ${tag.description ?? ""}`.trim()
        ),
      }))
    );

    for (const tag of aiL1Tags) {
      const key = tag.name.toLowerCase();
      if (tagMap.has(key)) continue;

      const candidateEmb = await generateEmbedding(
        projectId,
        `${tag.name} ${tag.description ?? ""}`.trim()
      );

      if (candidateEmb) {
        let maxSim = 0;
        let bestMatchId: number | undefined;
        for (const existEmb of existingL1Embeddings) {
          if (!existEmb.embedding) continue;
          const sim = cosineSimilarity(candidateEmb, existEmb.embedding);
          if (sim > maxSim) {
            maxSim = sim;
            bestMatchId = existEmb.id;
          }
        }
        if (maxSim >= similarityThreshold && bestMatchId !== undefined) {
          tagMap.set(key, bestMatchId);
          continue;
        }
      }

      try {
        const [created] = await tx
          .insert(l1TagsTable)
          .values({
            name: tag.name,
            category: tag.category ?? "Feature",
            description: tag.description,
            isAnchored: false,
          })
          .returning();
        tagMap.set(key, created.id);
        l1TagsCreated++;

        await tx.insert(reviewTasksTable).values({
          entityType: "l1_tag",
          entityId: created.id,
          taskType: "anchor",
          status: "pending",
          description: `New L1 tag "${tag.name}" generated by AI — review and anchor if accurate`,
        });
        reviewTasksCreated++;
      } catch {
        const [existing] = await tx
          .select()
          .from(l1TagsTable)
          .where(eq(l1TagsTable.name, tag.name));
        if (existing) tagMap.set(key, existing.id);
      }
    }

    if (l1TagsCreated > 0) {
      await tx.insert(activityLogTable).values({
        type: "tag_added",
        description: `AI generated ${l1TagsCreated} L1 tags for "${projectName}"`,
        projectId,
      });
    }

    return { l1TagsCreated, reviewTasksCreated, tagMap };
  }
}
